### ISSUE TITLE
less 实现在一定范围内循环

### ISSUE THREAD

**Issue by iotale** [iotale/garden#14]
与Sass不同，Less （目前v3.12.0）中没有用于编写循环的内置 `@for` 或 `@each` 指令，但它仍然可以使用递归 mixins 编写。递归mixins 只不过是一个不断调用自己的混合。

使用 Less 编写的循环有四个关键条件：

1. 带有 guard 表达式的 mixin，当满足循环的退出标准时，用于终止循环。类似 JavaScript  for 循环语句（ `for([initialization]; [condition]; [final-expression]) `）中的 [condition]
2. 对 mixin 执行第一次迭代的调用
3. 从内部调用 mixin 以使其递归
4. mixin 的其他内容等同于 JS for 循环语句的 statement 部分，即需要在循环内执行的部分

下面这个例子，是实现在一定范围内进行循环。注意动态的选择器写法和content的值必须是字符串。

```less
// when 后面跟着 guard 表达式，用来设定循环范围，并在条件满足时终止循环
.for-loop(@index, @min, @max) when ((@index >= @min) and (@index <= @max)) {
  // statement
  .item {
    &[data-value="@{index}px"]::before {
      content: "@{index}px";
      font-size: @index + 0px;
    }
  }
  // 内部调用，递归
  .for-loop(@index + 1, @min, @max);
}
// 第一次迭代调用
.for-loop(20, 20, 22);
```

**编译为CSS：**

```css
.item[data-value="20px"]::before {
  content: "20px";
  font-size: 20px;
}
.item[data-value="21px"]::before {
  content: "21px";
  font-size: 21px;
}
.item[data-value="22px"]::before {
  content: "22px";
  font-size: 22px;
}
```
