### ISSUE TITLE
由 “background-size 位置对 background 效果的影响“看 CSS 的书写顺序

### ISSUE THREAD

**Issue by iotale** [iotale/garden#15]
### 问题描述

在使用 CSS3 的 `linear-gradient()` 函数绘制一个[网格背景](https://codepen.io/iotale/full/qBaryXy)的时候，遇到了一个奇怪的问题：当将 `background-size` 放到 `background: linear-gradient()` 前面时，渐变背景的效果就失效了。放在后面就又正常了。

正常显示时代码：

```css
.example {
  width: 300px;
  height: 300px;
  background: linear-gradient(to top, transparent 39px, blue 40px),
    linear-gradient(to left, transparent 39px, blue 40px);
  background-size: 40px 40px;
}
```

![网格线背景](https://cdn.jsdelivr.net/gh/iotale/pic@master/uPic/G8adkT.png)

但是当将 `background-size` 移到 `background: linear-gradient()` 前面时：

```css
.example {
  background-size: 40px 40px;
  background: linear-gradient(to top, transparent 39px, blue 40px),
    linear-gradient(to left, transparent 39px, blue 40px);
}
```

![渐变失效](https://cdn.jsdelivr.net/gh/iotale/pic@master/uPic/qyWnpd.png)

其实不仅是渐变背景，使用图片背景时，也会因此而导致背景图片的大小和 `repeat` 特性变得不受控制。毕竟渐变其实是一种特殊的 image 背景。

> CSS `linear-gradient()` 函数用于创建一个表示两种或多种颜色线性渐变的图片。其结果属于 `<gradient>` 数据类型，是一种特别的 `<image>` 数据类型。—— [MDN](<https://developer.mozilla.org/zh-CN/docs/Web/CSS/linear-gradient()>)

### 原因分析

**原因很简单，其实就是 `background` 属性简写造成的。**

我们知道 CSS 中只写 `background` 时，是一种属性的简写，会**隐式声明**背景的多个属性，包括 `background-clip`、`background-color`、`background-image`、`background-origin`、`background-position`、`background-repeat`、`background-size`，和 `background-attachment`。

另外，在*同一选择器中重复声明多条相同的属性*（如果不在意编辑器的警告），后面声明的属性值会**覆盖**前面的属性值。因为 CSS 的语句是**顺序**‘执行’的。

因此，如果将 `background-size` 放在 `background` 前面，实际上 `background` 中隐式声明的 `background-size` 会覆盖前面的显式声明，就像这样：

```css
.example {
  background-size: 40px 40px;
  background-size: auto auto;
  /* background-size 的初始值是 auto auto */
}
```

而如果将显式声明的 `background-size` 放在 `background` 后面，那就是显式声明覆盖属性简写中的隐式声明，所以显式声明的属性就生效了

```css
.example {
  background-size: auto auto;
  background-size: 40px 40px;
}
```

### 解决

- 原因分析中提到的，修正覆盖顺序，将显式声明的 `background-size` 放在 `background` 后面
- 不使用 `background` 简写，而是改成 `background-image`，此时不会发生覆盖，所以顺序可以是任意的了

  ```css
  .example {
    background-size: 40px 40px;
    background-image: linear-gradient(to top, transparent 39px, blue 40px),
      linear-gradient(to left, transparent 39px, blue 40px);
  }
  ```

- 只用简写

  `background` 的简写还需要注意一点，“<bg-size>” 只能紧接着 “<position>” 出现，并且以"/"分割，比如 `0 0/40px 40px` 表示 `background-position-x background-position-y/background-size`。

另外要注意一点，`background-size` 如果仅有一个数值被给定，这个数值将作为宽度值大小，高度值将被设定为 `auto`。

  ```css
  background: linear-gradient(to right, transparent 39px, blue 40px) 0 0/40px 40px,
    linear-gradient(to bottom, transparent 39px, blue 40px) 0 0/40px 40px;
  ```

### 书写顺序

说到 CSS 的优先级规则，一般想到的是“选择器的权重”或者“同名选择器时的优先级”，又或者“同一元素有多个选择器时的样式层叠效果”。这里实际上是在**同一选择器中声明属性时区分顺序**的情况，只有两条：

- 相同属性：根据代码先后顺序，后面声明的属性值会覆盖前面的
- 一个属性是另一个属性和其他属性的简写：如上 `background` 发生的隐式声明和显式声明之间的覆盖，其实还是相同属性的书写顺序问题

### PS：`linear-gradient` 语法说明

最终语法：

```
linear-gradient([ [ [ <angle> | to [top | bottom] || [left | right] ],]? <color-stop>[, <color-stop>]+);
```

当使用带前缀的规则时，不要加“`to`”关键字。不带前缀且没有 `to` 关键词的语法会被丢弃。to top, to bottom, to left 和 to right这些值会被转换成角度0度、180度、270度和90度。其余值会被转换为一个以向顶部中央方向为起点顺时针旋转的角度。

```css
.grad {
  background-color: #F07575; /* 不支持渐变的浏览器回退方案 */
  background-image: -webkit-linear-gradient(top, hsl(0, 80%, 70%), #bada55); /* 支持 Chrome 25 and Safari 6, iOS 6.1, Android 4.3 */
  background-image:    -moz-linear-gradient(top, hsl(0, 80%, 70%), #bada55); /* 支持 Firefox (3.6 to 15) */
  background-image:      -o-linear-gradient(top, hsl(0, 80%, 70%), #bada55); /* 支持旧 Opera (11.1 to 12.0) */
  background-image:         linear-gradient(to bottom, hsl(0, 80%, 70%), #bada55); /* 标准语法; 需要最新版本 */
}
```
