### ISSUE TITLE
input[type=file] 调用原生相机和相册功能

### ISSUE THREAD

**Issue by iotale** [iotale/garden#26]
最近遇到一个业务场景，需要在 H5 页面中调用手机摄像头。思来想去没有头绪（基础知识不扎实啊）。后来看到 `<input>` 可以实现。学习了。

### HTMLInputElement API: `type="file"`

`<input>` 元素有个选择文件的功能，它会打开系统的文件选择器：

```html
<input type="file" />
```

但是如果只是一个 `type="file"` 属性还不足以让手机打开相机功能，还要设置 input 接受的文件类型。

#### `accept` 属性

如果 `accept`  属性指出了 input 是图片或者视频类型，那么移动端在上传文件的时候，操作系统会让用户做出选择，通过拍照或者通过选择系统文件来实现上传。使用下面代码就可以实现：

```html
<!-- 在Android和IOS中均会先显示打开相机还是打开系统文件 -->
<input type="file" accept="image/*"  />
```

#### `capture` 属性

如果只是想要打开相机，不需要打开系统文件选择的话，可以设置 capture 属性为一个字符串。（测试 IOS14 和 Android10 自带 browser 均只打开相机）

```html
<input type="file" accept="image/*" capture="camera" />
```

> Note these work better on mobile devices; if your device is a desktop computer, you'll likely get a typical file picker.

从 caniuse 中可以看到，web 端全部阵亡，移动端基本支持：

![](https://cdn.jsdelivr.net/gh/iotale/pic@master/uPic/inputcapture.png)

实际上新的 capture 属性只有两个值：

- `user` 表示应该使用前置摄像头和/或麦克风
- `environment` 表示应该使用后置摄像头和/或麦克风

缺少此属性，则 user agent 可以自由决定做什么。如果请求的前置模式不可用，则用户代理可能退回到其首选的默认模式。

如果是其它非空字符串值（例如capture="camera"），会当做布尔值 `true` 处理，则该布尔属性要求使用设备的媒体捕获设备（例如相机或麦克风）而不是请求文件输入。

#### 样式修改

默认样式多少有点不满足我们的业务需求，所以需要对控件进行样式修改。

<img src="https://cdn.jsdelivr.net/gh/iotale/pic@master/uPic/image.png" style="zoom:80%;float:left" />

优化方法有很多，这里只用最简单的方法：通过外层嵌套一个容器，将想要的样式和内容放在这个容器，然后将 `input[type=file]` 的元素通过 `opacity:0` 隐藏掉即可。`opacity:0` 隐藏的好处是元素依然存在DOM树上，且点击事件正常。

```html
<span class="box">打开相机
  <input class="input" id="camera" type="file" accept="image/*"  />
</span>
```

CSS样式修改

```css
.box {
  position: relative;
  display: inline-block;
  overflow: hidden;
  background: lightblue;
  color: darkred;
  padding: 20px;
  border-radius: 4px;
  margin: 4px;
  font-size: 16px;
  font-weight: 600;
}
.box .input {
  position: absolute;
  right: 0;
  top: 0;
  opacity: 0;
  filter: alpha(opacity=0);/兼容ie/
  cursor: pointer;
  height: 100%;
}
```

最终效果：

<img src="https://cdn.jsdelivr.net/gh/iotale/pic@master/uPic/sdisdciamsa.png" style="zoom:67%;float:left;" />

### 参考：

- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture

- https://amamiryoin.github.io/2018/05/11/js%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%B0%83%E7%94%A8%E6%91%84%E5%83%8F%E5%A4%B4%E6%8B%8D%E7%85%A7%E5%B9%B6%E5%AE%9E%E7%8E%B0%E4%B8%8A%E4%BC%A0/
